files:
  include:
    - 'styles/**/*.scss'

options:
  formatter: stylish
  merge-default-rules: false

rules:
  bem-depth:
    - 0
    - max-depth: 1

  border-zero: 2

  brace-style: 2

  class-name-format:
    - 0
    - convention: hyphenatedbem

  clean-import-paths:
    - 2
    - filename-extension: false
      leading-underscore: false

  declarations-before-nesting: 2

  empty-line-between-blocks: 2

  final-newline: 2

  function-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase

  hex-length:
    - 2
    - style: short

  hex-notation:
    - 2
    - style: lowercase

  indentation:
    - 2
    - size: 2

  leading-zero: 0

  mixin-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase

  mixins-before-declarations: 2

  nesting-depth:
    - 2
    - max-depth: 3

  no-color-literals: 2

  no-css-comments: 2

  no-debug: 2

  # TODO: Remove cursor from exclude list when cleaning up 'no-vendor-prefixes'
  no-duplicate-properties:
    - 2
    - exclude: ['src', 'cursor']

  no-empty-rulesets: 2

  no-extends: 2

  no-ids: 2

  # TODO: Overwriting third party CSS, will come back to this with CSS cleanup
  no-important: 0

  no-invalid-hex: 2

  no-mergeable-selectors: 2

  no-misspelled-properties: 2

  # TODO: Overwriting third party CSS, will come back to this with CSS cleanup
  no-qualifying-elements:
    - 0
    - allow-element-with-attribute: false
      allow-element-with-class: false
      allow-element-with-id: false

  no-trailing-whitespace: 2

  no-trailing-zero: 2

  no-url-protocols: 2

  # TODO: Only 2 instances, but needs lots of testing, will come back to this with CSS cleanup
  no-vendor-prefixes:
    - 0
    - additional-identifiers: []
      excluded-identifiers: []

  placeholder-in-extend: 2

  placeholder-name-format:
    - 2
    - convention: hyphenatedbem

  # TODO: Nice to have properties alphabetized, but not important
  property-sort-order: 0

  property-units:
    - 2
    - global:
        - em
        - rem
        - px
        - vh
        - vw
        - vmin
        - vmax
        - s
        - ms

  quotes:
    - 2
    - style: single

  shorthand-values: 2

  single-line-per-selector: 2

  space-after-bang: 2

  space-after-colon: 2

  space-after-comma: 2

  space-before-bang: 2

  space-before-brace: 2

  space-before-colon: 2

  space-between-parens: 2

  trailing-semicolon: 2

  url-quotes: 2

  variable-for-property: 2

  variable-name-format:
    - 2
    - allow-leading-underscore: false
      convention: hyphenatedlowercase

  zero-unit: 2
